# Generated by Django 2.1.5 on 2019-02-12 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('status', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Votant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_sent', models.BooleanField(default=False)),
                ('vote_ok', models.BooleanField(default=False)),
                ('token', models.CharField(default=uuid.UUID('f32881d0-ae60-4bf3-ae8e-c0bdf30d8854'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('liste_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list1', to='app.Liste')),
                ('liste_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list2', to='app.Liste')),
                ('liste_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list3', to='app.Liste')),
                ('liste_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list4', to='app.Liste')),
            ],
        ),
    ]
