# Generated by Django 2.1.5 on 2019-02-14 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_votant_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votant',
            name='id',
        ),
        migrations.AddField(
            model_name='votant',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
