# Generated by Django 2.1.5 on 2019-02-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190214_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='votant',
            name='email_reminder_sent',
            field=models.BooleanField(default=False),
        )
    ]
