# Generated by Django 2.1.5 on 2019-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190216_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
